Fix possible IndexOutOfBoundsException in MarkFile constructor which creates the parent directory.
java.lang.IndexOutOfBoundsException: index=16 length=8 capacity=16
	at org.agrona.AbstractMutableDirectBuffer.boundsCheck0(AbstractMutableDirectBuffer.java:1732)
	at org.agrona.concurrent.UnsafeBuffer.getLongVolatile(UnsafeBuffer.java:382)
	at org.agrona.MarkFile.isActive(MarkFile.java:713)
	at org.agrona.MarkFile.ensureDirectoryExists(MarkFile.java:424)
	at org.agrona.MarkFile.<init>(MarkFile.java:92)

ensureDirectoryExists maps a subregion of the mark file,
so we need to change absolute offsets into relative ones.